# <----- pubspec.yaml ----->
name: netflix_test
description: "Netflix Film Ä°zleme App"
publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  csv:
  http:
  fl_chart:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  
  assets:
    - assets/NetflixFilmHistory.csv
