name: netflix_watchlist_v2_app
description: "Netflix watch list App v2"
publish_to: 'none'

version: 2.0.6+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8           # iOS stilinde ikonlar

  csv:                             # CSV dosyalarını okuma/yazma
  http:                            # HTTP istekleri (GET/POST)
  fl_chart:                        # Grafik ve şema oluşturma

  # -----------------------------
  # Uygulama bilgisi
  # -----------------------------
  package_info_plus:               # Uygulama sürümü, build numarası, paket adı
  device_info_plus:                # Cihaz modeli, Android/iOS sürümü

  # -----------------------------
  # İzinler
  # -----------------------------
  permission_handler:              # Çalışma zamanı izinleri (Android/iOS)

  # -----------------------------
  # Veritabanı / Depolama
  # -----------------------------
  path_provider:                   # Belgeler/Geçici/İndirilenler dizinleri (platforma özel)
  path:                            # Dosya yolu işlemleri (join/dirname/extension)
  external_path:                   # Android harici depolama (Downloads/DCIM) yolu erişimi

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/database/NetflixFilmHistory.csv
    - assets/images/
